stages:
    download_data:
        cmd: bash scripts/download_datasets.sh
        deps:
            - scripts/download_datasets.sh
        outs:
            - data/detox_train.tsv
            - data/detox_dev.tsv
            - data/detox_test.tsv
            - data/2ch.csv
            - data/ok.ft
            - data/persona.tsv
            - data/koziev.txt
            - data/bad_vocab.txt
            - data/seq2seq_gen.jsonl
            - data/seq2seq_gen_train.jsonl
            - data/seq2seq_gen_val.jsonl

    prepare_seq2seq_dataset:
        cmd:
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_train.tsv
                --output-file data/seq2seq_train.jsonl
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_dev.tsv
                --output-file data/seq2seq_val.jsonl
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_train.tsv
                --output-file data/seq2seq_train_extended.jsonl
                --include-auto-neutrals
                --include-auto-toxic
                --include-reverse
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_dev.tsv
                --output-file data/seq2seq_val_extended.jsonl
                --include-auto-neutrals
                --include-auto-toxic
                --include-reverse
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_test.tsv
                --output-file  data/seq2seq_test.jsonl
            - python3 -m rudetox.seq2seq.augment
                --input-path data/seq2seq_train.jsonl
                --output-path data/seq2seq_train_aug.jsonl
                --config-path configs/seq2seq_augmentations.json
                --bad-vocab-path data/bad_vocab.txt
            - python3 -m rudetox.seq2seq.augment
                --input-path data/seq2seq_val.jsonl
                --output-path data/seq2seq_val_aug.jsonl
                --config-path configs/seq2seq_augmentations.json
                --bad-vocab-path data/bad_vocab.txt
        deps:
            - rudetox/seq2seq/converters/detox.py
            - rudetox/seq2seq/augment.py
            - configs/seq2seq_augmentations.json
            - data/detox_train.tsv
            - data/detox_dev.tsv
            - data/detox_test.tsv
            - data/bad_vocab.txt
        outs:
            - data/seq2seq_train.jsonl
            - data/seq2seq_train_aug.jsonl
            - data/seq2seq_val.jsonl
            - data/seq2seq_val_aug.jsonl
            - data/seq2seq_test.jsonl
            - data/seq2seq_train_extended.jsonl
            - data/seq2seq_val_extended.jsonl

    prepare_clf_dataset:
        cmd:
            - bash scripts/prepare_clf_dataset.sh
        deps:
            - scripts/prepare_clf_dataset.sh
            - rudetox/clf/converters/detox.py
            - rudetox/clf/converters/ok.py
            - rudetox/clf/converters/2ch.py
            - rudetox/clf/converters/persona.py
            - rudetox/clf/converters/koziev.py
            - rudetox/clf/merge_all.py
            - rudetox/clf/clean.py
            - rudetox/clf/split.py
            - rudetox/clf/augment.py
            - data/detox_train.tsv
            - data/ok.ft
            - data/2ch.csv
            - data/persona.tsv
            - data/koziev.txt
            - data/bad_vocab.txt
            - configs/augmentations.json
        outs:
            - data/clf_all.jsonl
            - data/clf_train.jsonl
            - data/clf_train_aug.jsonl
            - data/clf_val.jsonl
            - data/clf_val_aug.jsonl
            - data/clf_test.jsonl

    download_models:
        cmd:
            - mkdir -p models
            - rm -rf models/sim models/fluency models/en_ru
                models/ru_en models/rubertconv models/sber_rut5_base
                models/orig_rut5_base
            - git clone https://huggingface.co/cointegrated/LaBSE-en-ru models/sim
            - git clone https://huggingface.co/SkolkovoInstitute/rubert-base-corruption-detector models/fluency
            - git clone https://huggingface.co/facebook/wmt19-en-ru models/en_ru
            - git clone https://huggingface.co/facebook/wmt19-ru-en models/ru_en
            - git clone https://huggingface.co/DeepPavlov/rubert-base-cased-conversational models/rubertconv
            - git clone https://huggingface.co/sberbank-ai/ruT5-base models/sber_rut5_base
            - git clone https://huggingface.co/cointegrated/rut5-base models/orig_rut5_base
        outs:
            - models/sim
            - models/fluency
            - models/en_ru
            - models/ru_en
            - models/rubertconv
            - models/orig_rut5_base
            - models/sber_rut5_base

    train_clf:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.clf.train
                --config-path configs/rubertconv_toxic_clf.json
                --train-path data/clf_train_aug.jsonl
                --val-path data/clf_val_aug.jsonl
                --test-path data/clf_test.jsonl
                --out-dir models/rubertconv_toxic_clf
            - rm -rf models/rubertconv_toxic_clf/checkpoint*
        deps:
            - rudetox/clf/train.py
            - configs/rubertconv_toxic_clf.json
            - data/clf_train_aug.jsonl
            - data/clf_val_aug.jsonl
            - data/clf_test.jsonl
        outs:
            - models/rubertconv_toxic_clf

    train_seq2seq:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train
                --config-path configs/rut5_detox.json
                --train-path data/seq2seq_train.jsonl
                --val-path data/seq2seq_val.jsonl
                --out-dir models/rut5_detox
            - rm -rf models/rut5_detox/checkpoint*
        deps:
            - rudetox/seq2seq/train.py
            - configs/rut5_detox.json
            - models/sber_rut5_base
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
        outs:
            - models/rut5_detox

    check_clf:
        cmd:
            - mkdir -p reports
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.clf.check
                --model-name models/rubertconv_toxic_clf
                --test-path data/clf_test.jsonl
                --toxic-vocab-path data/bad_vocab.txt
                --sample-rate 0.1
                --save-path reports/clf_suite.pkl
        deps:
            - models/rubertconv_toxic_clf
            - rudetox/clf/check.py
            - data/clf_test.jsonl
            - data/bad_vocab.txt
        outs:
            - reports/clf_suite.pkl

    predict_seq2seq:
        cmd:
            - mkdir -p predictions
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.predict
                --input-file data/seq2seq_test.jsonl
                --output-file predictions/rut5_detox_ranker.jsonl
                --model-name models/rut5_detox
                --num-beams 4
                --num-return-sequences 4
                --batch-size 4
                --ranker-config configs/ranker.json
        deps:
            - rudetox/seq2seq/predict.py
            - models/rut5_detox
            - models/rubertconv_toxic_clf
            - models/fluency
            - models/sim
            - configs/ranker.json
            - data/seq2seq_test.jsonl
        outs:
            - predictions/rut5_detox_ranker.jsonl

    sample_toxic:
        cmd:
            - python3 -m rudetox.sample
                data/clf_all.jsonl data/toxic.jsonl
                --config-path configs/toxic_sampler.json
        deps:
            - rudetox/sample.py
            - configs/toxic_sampler.json
            - data/clf_all.jsonl
        outs:
            - data/toxic.jsonl

    sample_neutral:
        cmd:
            - python3 -m rudetox.sample
                data/clf_all.jsonl data/neutral.jsonl
                --config-path configs/neutral_sampler.json
        deps:
            - rudetox/sample.py
            - configs/neutral_sampler.json
            - data/clf_all.jsonl
        outs:
            - data/neutral.jsonl

    gen_toxic2neutral_backtrans:
        cmd:
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.backtrans
                data/toxic.jsonl data/backtrans_toxic2neutral.jsonl
                --num-beams 5
                --forward-model-name models/ru_en
                --backward-model-name models/en_ru
        deps:
            - rudetox/backtrans.py
            - data/toxic.jsonl
            - models/ru_en
            - models/en_ru
        outs:
            - data/backtrans_toxic2neutral.jsonl

    train_reverse_seq2seq:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train
                --config-path configs/rut5_tox.json
                --train-path data/seq2seq_train.jsonl
                --val-path data/seq2seq_val.jsonl
                --out-dir models/rut5_tox
                --source-field "target"
                --target-field "source"
            - rm -rf models/rut5_tox/checkpoint*
        deps:
            - rudetox/seq2seq/train.py
            - configs/rut5_tox.json
            - models/sber_rut5_base
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
        outs:
            - models/rut5_tox

    predict_reverse_seq2seq:
        cmd:
            - mkdir -p predictions
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.predict
                --input-file data/neutral.jsonl
                --source-field text
                --sample-rate 0.03
                --output-file data/reverse_neutral2toxic.jsonl
                --model-name models/rut5_tox
                --num-beams 20
                --num-return-sequences 20
                --batch-size 2
        deps:
            - models/rut5_tox
            - rudetox/seq2seq/predict.py
            - data/neutral.jsonl
        outs:
            - data/reverse_neutral2toxic.jsonl

    rank_neutral2toxic_reverse_seq2seq:
        cmd:
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.ranker
                data/reverse_neutral2toxic.jsonl data/reverse_neutral2toxic_ranked.jsonl
                --config-path configs/inverse_ranker.json
                --source-field text
                --target-field target
        deps:
            - rudetox/ranker.py
            - data/reverse_neutral2toxic.jsonl
            - configs/inverse_ranker.json
        outs:
            - data/reverse_neutral2toxic_ranked.jsonl

    finalize_neutral2toxic_reverse_seq2seq:
        cmd:
            - python3 -m rudetox.filter
                data/reverse_neutral2toxic_ranked.jsonl
                data/reverse_neutral2toxic_final.jsonl
                --config-path configs/inverse_filter.json
                --source-field target
                --target-field source
        deps:
            - rudetox/filter.py
            - configs/inverse_filter.json
            - data/reverse_neutral2toxic_ranked.jsonl
        outs:
            - data/reverse_neutral2toxic_final.jsonl

    train_marker:
        cmd:
            - python3 -m rudetox.marker.compute_tags
                data/seq2seq_train.jsonl data/marker_train.jsonl
                --model-name models/rubertconv
            - python3 -m rudetox.marker.compute_tags
                data/seq2seq_val.jsonl data/marker_val.jsonl
                --model-name models/rubertconv
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.marker.train
                --train-path data/marker_train.jsonl
                --val-path data/marker_val.jsonl
                --out-dir models/rubertconv_toxic_marker
                --config-path configs/rubertconv_toxic_marker.json
                --text-field orig_source
                --labels-field labels
            - rm -rf models/rubertconv_toxic_marker/checkpoint*
        deps:
            - rudetox/marker/compute_tags.py
            - rudetox/marker/train.py
            - configs/rubertconv_toxic_marker.json
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
            - models/rubertconv
        outs:
            - data/marker_train.jsonl
            - data/marker_val.jsonl
            - models/rubertconv_toxic_marker


    train_nontoxic_mlm:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train_mlm
                --config-path configs/rut5_mlm.json
                --input-path data/nontoxic.jsonl
                --text-field text
                --out-dir models/rut5_nontoxic_mlm
                --override-base-model models/orig_rut5_base
            - rm -rf models/rut5_nontoxic_mlm/checkpoint*
        deps:
            - rudetox/seq2seq/train_mlm.py
            - configs/rut5_mlm.json
            - data/nontoxic.jsonl
            - models/orig_rut5_base
        outs:
            - models/rut5_nontoxic_mlm

    fill_with_marker:
        cmd:
            - CUDA_VISIBLE_DEVICE=0 python3 -m rudetox.marker.fill
                --model-name models/rubertconv_toxic_marker
                --input-path data/toxic.jsonl
                --output-path data/marker_toxic2neutral.jsonl
                --filler-model-name models/orig_rut5_base
                --text-field "text"
        deps:
            - rudetox/marker/fill.py
            - data/toxic.jsonl
            - models/rubertconv_toxic_marker
            - models/rubertconv
        outs:
            - data/marker_toxic2neutral.jsonl

    rank_toxic2neutral:
        cmd:
            - cat data/backtrans_toxic2neutral.jsonl > data/toxic2neutral.jsonl
            - cat data/marker_toxic2neutral.jsonl >> data/toxic2neutral.jsonl
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.ranker
                data/toxic2neutral.jsonl
                data/toxic2neutral_ranked.jsonl
                --config-path configs/ranker.json
                --source-field source
                --target-field target
        deps:
            - rudetox/ranker.py
            - configs/ranker.json
            - data/backtrans_toxic2neutral.jsonl
            - data/marker_toxic2neutral.jsonl
        outs:
            - data/toxic2neutral_ranked.jsonl

    finalize_toxic2neutral:
        cmd:
            - python3 -m rudetox.filter
                data/toxic2neutral_ranked.jsonl
                data/toxic2neutral_final.jsonl
                --config-path configs/filter.json
                --source-field source
                --target-field target
        deps:
            - rudetox/filter.py
            - configs/filter.json
            - data/toxic2neutral_ranked.jsonl
        outs:
            - data/toxic2neutral_final.jsonl


