stages:
    download_data:
        cmd: bash scripts/download_datasets.sh
        deps:
            - scripts/download_datasets.sh
        outs:
            - data/detox_train.tsv
            - data/detox_dev.tsv
            - data/detox_test.tsv
            - data/2ch.csv
            - data/ok.ft
            - data/persona.tsv
            - data/koziev.txt
            - data/bad_vocab.txt
            - data/seq2seq_gen.jsonl
            - data/seq2seq_gen_train.jsonl
            - data/seq2seq_gen_val.jsonl

    prepare_seq2seq_dataset:
        cmd:
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_train.tsv
                --output-file data/seq2seq_train.jsonl
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_dev.tsv
                --output-file data/seq2seq_val.jsonl
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_train.tsv
                --output-file data/seq2seq_train_extended.jsonl
                --include-auto-neutrals
                --include-auto-toxic
                --include-reverse
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_dev.tsv
                --output-file data/seq2seq_val_extended.jsonl
                --include-auto-neutrals
                --include-auto-toxic
                --include-reverse
            - python3 -m rudetox.seq2seq.converters.detox
                --input-file data/detox_test.tsv
                --output-file  data/seq2seq_test.jsonl
            - python3 -m rudetox.seq2seq.augment
                --input-path data/seq2seq_train.jsonl
                --output-path data/seq2seq_train_aug.jsonl
                --config-path configs/seq2seq_augmentations.json
                --bad-vocab-path data/bad_vocab.txt
            - python3 -m rudetox.seq2seq.augment
                --input-path data/seq2seq_val.jsonl
                --output-path data/seq2seq_val_aug.jsonl
                --config-path configs/seq2seq_augmentations.json
                --bad-vocab-path data/bad_vocab.txt
        deps:
            - rudetox/seq2seq/converters/detox.py
            - rudetox/seq2seq/augment.py
            - configs/seq2seq_augmentations.json
            - data/detox_train.tsv
            - data/detox_dev.tsv
            - data/detox_test.tsv
            - data/bad_vocab.txt
        outs:
            - data/seq2seq_train.jsonl
            - data/seq2seq_train_aug.jsonl
            - data/seq2seq_val.jsonl
            - data/seq2seq_val_aug.jsonl
            - data/seq2seq_test.jsonl
            - data/seq2seq_train_extended.jsonl
            - data/seq2seq_val_extended.jsonl

    prepare_clf_dataset:
        cmd:
            - bash scripts/prepare_clf_dataset.sh
        deps:
            - scripts/prepare_clf_dataset.sh
            - rudetox/clf/converters/detox.py
            - rudetox/clf/converters/ok.py
            - rudetox/clf/converters/2ch.py
            - rudetox/clf/converters/persona.py
            - rudetox/clf/converters/koziev.py
            - rudetox/clf/merge_all.py
            - rudetox/clf/clean.py
            - rudetox/clf/split.py
            - rudetox/clf/augment.py
            - data/detox_train.tsv
            - data/ok.ft
            - data/2ch.csv
            - data/persona.tsv
            - data/koziev.txt
            - data/bad_vocab.txt
            - configs/augmentations.json
        outs:
            - data/clf_all.jsonl
            - data/clf_train.jsonl
            - data/clf_train_aug.jsonl
            - data/clf_val.jsonl
            - data/clf_val_aug.jsonl
            - data/clf_test.jsonl

    download_models:
        cmd:
            - mkdir -p models
            - rm -rf models/sim models/fluency models/en_ru
                models/ru_en models/rubertconv models/sber_rut5_base
                models/orig_rut5_base
            - git clone https://huggingface.co/cointegrated/LaBSE-en-ru models/sim
            - git clone https://huggingface.co/SkolkovoInstitute/rubert-base-corruption-detector models/fluency
            - git clone https://huggingface.co/facebook/wmt19-en-ru models/en_ru
            - git clone https://huggingface.co/facebook/wmt19-ru-en models/ru_en
            - git clone https://huggingface.co/DeepPavlov/rubert-base-cased-conversational models/rubertconv
            - git clone https://huggingface.co/sberbank-ai/ruT5-base models/sber_rut5_base
            - git clone https://huggingface.co/cointegrated/rut5-base models/orig_rut5_base
        outs:
            - models/sim
            - models/fluency
            - models/en_ru
            - models/ru_en
            - models/rubertconv
            - models/orig_rut5_base
            - models/sber_rut5_base

    train_clf:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.clf.train
                --config-path configs/rubertconv_toxic_clf.json
                --train-path data/clf_train_aug.jsonl
                --val-path data/clf_val_aug.jsonl
                --test-path data/clf_test.jsonl
                --out-dir models/rubertconv_toxic_clf
                --override-base-model models/rubertconv
            - rm -rf models/rubertconv_toxic_clf/checkpoint*
        deps:
            - rudetox/clf/train.py
            - configs/rubertconv_toxic_clf.json
            - data/clf_train_aug.jsonl
            - data/clf_val_aug.jsonl
            - data/clf_test.jsonl
            - models/rubertconv
        outs:
            - models/rubertconv_toxic_clf

    check_clf:
        cmd:
            - mkdir -p reports
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.clf.check
                --model-name models/rubertconv_toxic_clf
                --test-path data/clf_test.jsonl
                --toxic-vocab-path data/bad_vocab.txt
                --sample-rate 0.1
                --save-path reports/clf_suite.pkl
        deps:
            - models/rubertconv_toxic_clf
            - rudetox/clf/check.py
            - data/clf_test.jsonl
            - data/bad_vocab.txt
        outs:
            - reports/clf_suite.pkl

    train_seq2seq_sber:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train
                --config-path configs/sber_rut5_detox.json
                --train-path data/seq2seq_train_aug.jsonl
                --val-path data/seq2seq_val_aug.jsonl
                --out-dir models/sber_rut5_detox
                --override-base-model models/sber_rut5_base
            - rm -rf models/sber_rut5_detox/checkpoint*
        deps:
            - rudetox/seq2seq/train.py
            - configs/sber_rut5_detox.json
            - models/sber_rut5_base
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
        outs:
            - models/sber_rut5_detox

    predict_seq2seq_sber:
        cmd:
            - mkdir -p predictions
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.predict
                --input-file data/seq2seq_test.jsonl
                --output-file predictions/seq2seq_sber_beam5.jsonl
                --model-name models/sber_rut5_detox
                --num-beams 5
                --num-return-sequences 5
                --batch-size 2
        deps:
            - rudetox/seq2seq/predict.py
            - models/sber_rut5_detox
            - models/rubertconv_toxic_clf
            - models/fluency
            - models/sim
            - configs/ranker.json
            - data/seq2seq_test.jsonl
        outs:
            - predictions/seq2seq_sber_beam5.jsonl

    train_seq2seq_orig:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train
                --config-path configs/orig_rut5_detox.json
                --train-path data/seq2seq_train_aug.jsonl
                --val-path data/seq2seq_val_aug.jsonl
                --out-dir models/orig_rut5_detox
                --override-base-model models/orig_rut5_base
            - rm -rf models/orig_rut5_detox/checkpoint*
        deps:
            - rudetox/seq2seq/train.py
            - configs/orig_rut5_detox.json
            - models/orig_rut5_base
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
        outs:
            - models/orig_rut5_detox

    predict_seq2seq_orig:
        cmd:
            - mkdir -p predictions
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.predict
                --input-file data/seq2seq_test.jsonl
                --output-file predictions/seq2seq_orig_beam5.jsonl
                --model-name models/orig_rut5_detox
                --num-beams 5
                --num-return-sequences 5
                --batch-size 2
        deps:
            - rudetox/seq2seq/predict.py
            - models/orig_rut5_detox
            - models/rubertconv_toxic_clf
            - models/fluency
            - models/sim
            - configs/ranker.json
            - data/seq2seq_test.jsonl
        outs:
            - predictions/seq2seq_orig_beam5.jsonl

    sample_toxic:
        cmd:
            - python3 -m rudetox.sample
                data/clf_all.jsonl data/toxic.jsonl
                --config-path configs/toxic_sampler.json
        deps:
            - rudetox/sample.py
            - configs/toxic_sampler.json
            - data/clf_all.jsonl
        outs:
            - data/toxic.jsonl

    sample_neutral:
        cmd:
            - python3 -m rudetox.sample
                data/clf_all.jsonl data/neutral.jsonl
                --config-path configs/neutral_sampler.json
        deps:
            - rudetox/sample.py
            - configs/neutral_sampler.json
            - data/clf_all.jsonl
        outs:
            - data/neutral.jsonl

    train_nontoxic_mlm_sber:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train_mlm
                --config-path configs/sber_rut5_nontoxic_mlm.json
                --input-path data/nontoxic.jsonl
                --text-field text
                --out-dir models/sber_rut5_nontoxic_mlm
                --override-base-model models/sber_rut5_base
            - rm -rf models/sber_rut5_nontoxic_mlm/checkpoint*
        deps:
            - rudetox/seq2seq/train_mlm.py
            - configs/sber_rut5_nontoxic_mlm.json
            - data/nontoxic.jsonl
            - models/sber_rut5_base
        outs:
            - models/sber_rut5_nontoxic_mlm

    train_marker:
        cmd:
            - python3 -m rudetox.marker.compute_tags
                data/seq2seq_train.jsonl data/marker_train.jsonl
                --model-name models/rubertconv
            - python3 -m rudetox.marker.compute_tags
                data/seq2seq_val.jsonl data/marker_val.jsonl
                --model-name models/rubertconv
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.marker.train
                --train-path data/marker_train.jsonl
                --val-path data/marker_val.jsonl
                --out-dir models/rubertconv_toxic_marker
                --config-path configs/rubertconv_toxic_marker.json
                --text-field orig_source
                --labels-field labels
                --choose-best
            - rm -rf models/rubertconv_toxic_marker/checkpoint*
        deps:
            - rudetox/marker/compute_tags.py
            - rudetox/marker/train.py
            - configs/rubertconv_toxic_marker.json
            - data/seq2seq_train.jsonl
            - data/seq2seq_val.jsonl
            - models/rubertconv
        outs:
            - data/marker_train.jsonl
            - data/marker_val.jsonl
            - models/rubertconv_toxic_marker

    train_filler_orig:
        cmd:
            - mkdir -p models
            - CUDA_VISIBLE_DEVICES=0 python3 -m rudetox.seq2seq.train
                --config-path configs/orig_rut5_filler.json
                --train-path data/marker_train.jsonl
                --val-path data/marker_val.jsonl
                --override-base-model models/orig_rut5_base
                --out-dir models/orig_rut5_filler
            - rm -rf models/orig_rut5_filler/checkpoint*
        deps:
            - rudetox/seq2seq/train.py
            - data/marker_train.jsonl
            - data/marker_val.jsonl
            - models/orig_rut5_base
        outs:
            - models/orig_rut5_filler
